### ISSUE TITLE
App does not open

### ISSUE THREAD

**Issue by mikehedman** [esper-io/esper-api-support-tool#163]
I downloaded the latest version mac_arm64_v0-195245_EsperApiSupportTool.app, and when I attempt to open it I see two entries in the Mac ActivityMonitor for about 20 seconds, and then they disappear.  I don't ever see the UI displayed.

![EAST](https://github.com/user-attachments/assets/1e860857-dc5b-43b5-8d32-3a27bb25aa4d)

I still have version mac_arm64_v0-194898_EsperApiSupportTool.app installed, and it runs fine - though it does suggest I should upgrade ;) .

**Comment by mikehedman** [comment]
In case it's helpful, here are the log entries (retrieved from the Console app).

Perhaps these two are the root:
default	16:13:12.326320-0700	mac_arm64_v0-195245_EsperApiSupportTool	Failed to execute script 'Main' due to unhandled exception: No module named 'sentry_sdk'
default	16:13:12.326375-0700	mac_arm64_v0-195245_EsperApiSupportTool	Traceback:
Traceback (most recent call last):
  File "Main.py", line 12, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "Utility/Logging/SentryUtils.py", line 4, in <module>
ModuleNotFoundError: No module named 'sentry_sdk'

**default**|**16:12:51.109657-0700**|**runningboardd**|**Launch request for app<application.com.esper.esperapisupporttool.199728057.199728065(502)>[0] is using uid 502 (divined from auid 502 euid 502)**
:-----:|:-----:|:-----:|:-----:
default|16:12:51.109735-0700|runningboardd|Acquiring assertion targeting app<application.com.esper.esperapisupporttool.199728057.199728065(502)> from originator [osservice<com.apple.Finder(502)>:980] with description <RBSAssertionDescriptor| "LS launch com.esper.esperapisupporttool" ID:410-980-15333 target:app<application.com.esper.esperapisupporttool.199728057.199728065(502)> attributes:[

**Comment by mikehedman** [comment]
mac_arm64_v0-195246_EsperApiSupportTool.app looks to have resolved the issue.  Thanks!
